<a href="https://colab.research.google.com/github/2303A52158/GENERATIVE-AI_2025/blob/main/Generative_AI_2303A52158_Ass_8_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**1. (1 ponto) Design a multilayer ANN architecture according to the requirements shown below.
Train, test, save (.h5) and deploy the model to predict the quality of wine using the Keras deep
learning library**

**2. (1 ponto) Calculate training and testing accuracy, build confusion matrix, also calculate recall,
precision and F1-score.**

**3. (1 ponto) Build the application by loading the saved ANN model.**

                              Tabela 1: ANN Architecture
              Layer         Neurons Activation Function
          Hidden Layer - 1    16         sigmoid
          Hidden Layer - 2    24         sigmoid
          Hidden Layer - 3    10         sigmoid

                              Tabela 2: Training Parameters

                        epochs batch-size error-metric Optimizer
                        260        64       accuracy    rmsprop

In [1]:
import tensorflow as tf
import pandas as pd
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import RMSprop
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

data = pd.read_csv('/content/winequality-red.csv')
X, y = data.iloc[:, :-1].to_numpy(), data.iloc[:, -1].to_numpy()

X_train, X_temp, y_train, y_temp = train_test_split(X, y, test_size=0.2, random_state=42)
X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.5, random_state=42)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_val_scaled = scaler.transform(X_val)
X_test_scaled = scaler.transform(X_test)

def wine_quality_model(input_shape):
    model = Sequential([
        Dense(16, activation='sigmoid', input_shape=(input_shape,)),
        Dense(24, activation='sigmoid'),
        Dense(10, activation='sigmoid'),
        Dense(1, activation='sigmoid')
    ])
    return model

model = wine_quality_model(X_train.shape[1])
model.compile(optimizer=RMSprop(), loss='binary_crossentropy', metrics=['accuracy'])

model.fit(X_train_scaled, y_train, validation_data=(X_val_scaled, y_val), epochs=260, batch_size=64, verbose=1)

model.save("wine_quality_model.h5")

train_loss, train_acc = model.evaluate(X_train_scaled, y_train, verbose=0)
test_loss, test_acc = model.evaluate(X_test_scaled, y_test, verbose=0)

print("Train Accuracy:", train_acc)
print("Test Accuracy:", test_acc)

y_pred = (model.predict(X_test_scaled) > 0.5).astype(int)
conf_matrix = confusion_matrix(y_test, y_pred)
report = classification_report(y_test, y_pred)

print("Confusion Matrix:\n", conf_matrix)
print("Classification Report:\n", report)

loaded_model = tf.keras.models.load_model("wine_quality_model.h5")

new_data = np.array([list(map(float, input().split()))])
new_data_scaled = scaler.transform(new_data)
predicted_result = loaded_model.predict(new_data_scaled)

print("Predicted Wine Quality (0: Bad, 1: Good):", int(predicted_result[0][0] > 0.5))


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Epoch 1/260
20/20 ━━━━━━━━━━━━━━━━━━━━ 10s 62ms/step - accuracy: 0.0000e+00 - loss: 4.7763 - val_accuracy: 0.0000e+00 - val_loss: 2.4781
Epoch 2/260
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - accuracy: 0.0000e+00 - loss: 1.8634 - val_accuracy: 0.0000e+00 - val_loss: 0.1091
Epoch 3/260
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - accuracy: 0.0000e+00 - loss: -0.4168 - val_accuracy: 0.0000e+00 - val_loss: -2.0456
Epoch 4/260
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - accuracy: 0.0000e+00 - loss: -2.4842 - val_accuracy: 0.0000e+00 - val_loss: -3.9705
Epoch 5/260
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - accuracy: 0.0000e+00 - loss: -4.3443 - val_accuracy: 0.0000e+00 - val_loss: -5.6385
Epoch 6/260
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step - accuracy: 0.0000e+00 - loss: -5.8690 - val_accuracy: 0.0000e+00 - val_loss: -7.0676
Epoch 7/260
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - accuracy: 0.0000e+00 - loss: -7.2978 - val_accuracy: 0.0000e+00 - val_loss: -8.2692
Epoch 8/260
20/20 ━━━━━━━━━━━━━━━━━━━

Train Accuracy: 0.0
Test Accuracy: 0.0
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step 


/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_

Confusion Matrix:
 [[ 0  0  0  0  0  0]
 [ 6  0  0  0  0  0]
 [66  0  0  0  0  0]
 [66  0  0  0  0  0]
 [19  0  0  0  0  0]
 [ 3  0  0  0  0  0]]
Classification Report:
               precision    recall  f1-score   support

           1       0.00      0.00      0.00       0.0
           4       0.00      0.00      0.00       6.0
           5       0.00      0.00      0.00      66.0
           6       0.00      0.00      0.00      66.0
           7       0.00      0.00      0.00      19.0
           8       0.00      0.00      0.00       3.0

    accuracy                           0.00     160.0
   macro avg       0.00      0.00      0.00     160.0
weighted avg       0.00      0.00      0.00     160.0

7.4 0.7 0.0 1.9 0.076 11.0 34.0 0.9978 3.51 0.56 9.4
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step
Predicted Wine Quality (0: Bad, 1: Good): 1
