<a href="https://colab.research.google.com/github/2303A52158/GENERATIVE-AI_2025/blob/main/Generative_AI_230303A52158_Ass_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**1. (1 ponto) Write Python code from scratch to find error metrics of deep learning model. Actual
values and deep learning model predicted values are shown in Table 1. Also compare the results
with the outcomes of libraries**

         Y_Actual               Y_Pred

           20                     20.5        
           30                     30.3
           40                     40.2
           50                     50.6
           60                     60.7

          Tabela 1: YActual Vs. YP red

In [5]:
import numpy as np
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from math import sqrt

In [6]:
y_actual = np.array([20, 30, 40, 50, 60])
y_pred = np.array([20.5, 30.3, 40.2, 50.6, 60.7])

In [15]:
mae = mean_absolute_error(y_actual, y_pred)
mse = mean_squared_error(y_actual, y_pred)
rmse = sqrt(mse)
r2 = r2_score(y_actual, y_pred)

In [16]:
print("Regression Metrics:")
print(f"Mean Absolute Error (MAE) {mae}")
print(f"Mean Squared Error (MSE): {mse}")
print(f"Root Mean Squared Error (RMSE): {rmse}")
print(f"R-squared (R²): {r2}")

Regression Metrics:
Mean Absolute Error (MAE) 0.4600000000000016
Mean Squared Error (MSE): 0.24600000000000147
Root Mean Squared Error (RMSE): 0.49598387070549127
R-squared (R²): 0.99877


In [19]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [21]:
mae_sklearn = mean_absolute_error(y_actual, y_pred)
mse_sklearn = mean_squared_error(y_actual, y_pred)
r2_sklearn = r2_score(y_actual, y_pred)

In [22]:
print("\nlibraries(scikit-learn):")
print(f"Mean Absolute Error (MAE): {mae_sklearn:.2f}")
print(f"Mean Squared Error (MSE): {mse_sklearn:.2f}")
print(f"R-squared (R²): {r2_sklearn:.2f}")


libraries(scikit-learn):
Mean Absolute Error (MAE): 0.46
Mean Squared Error (MSE): 0.25
R-squared (R²): 1.00


**2. (1 ponto) Write python code from scratch to find evaluation metrics of deep learning model.
Actual values and deep learning model predicted values are shown in Table 2. Also compare the
results with outcome of libraries**

          Y_Actual              Y_Pred
            0                     0      1  1  2  0
            0                     0      1  0  2  0
            0                     1      1  2  2  1
            0                     2      1  0  2  2
            0                     2      1  2  2  2
              Tabela 2: YActual Vs. YP red

In [23]:
import numpy as np
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score

In [24]:
y_actual = np.array([0, 0, 0, 0, 0])
y_pred = np.array([
    [0, 1, 1, 2, 0],
    [0, 1, 0, 2, 0],
    [1, 1, 2, 2, 1],
    [0, 2, 1, 0, 2],
    [2, 1, 2, 2, 2],
])

In [30]:
y_actual = np.repeat(y_actual, y_pred.shape[1])
y_pred = y_pred.flatten()

In [31]:
conf_matrix = confusion_matrix(y_actual, y_pred)
accuracy = accuracy_score(y_actual, y_pred)
precision = precision_score(y_actual, y_pred, average='macro', zero_division=0)
recall = recall_score(y_actual, y_pred, average='macro', zero_division=0)
f1 = f1_score(y_actual, y_pred, average='macro', zero_division=0)

In [34]:
print("Confusion Matrix:")
print(conf_matrix)
print("\nEvaluation Metrics:")
print(f"Accuracy: {accuracy}")
print(f"Precision: {precision}")
print(f"Recall: {recall}")
print(f"F1-Score: {f1}")

Confusion Matrix:
[[ 7  8 10]
 [ 0  0  0]
 [ 0  0  0]]

Evaluation Metrics:
Accuracy: 0.28
Precision: 0.3333333333333333
Recall: 0.09333333333333334
F1-Score: 0.14583333333333334


In [35]:
import numpy as np
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report

Y_actual = np.array([0, 0, 1, 1, 2, 0, 0, 0, 1, 0, 2, 0, 0, 1, 1, 2, 2, 1, 0, 2, 1, 0, 2, 2, 0, 2, 1, 2, 2, 2])
Y_pred = np.array([0, 0, 1, 0, 2, 0, 0, 1, 1, 2, 2, 1, 0, 2, 1, 0, 2, 2, 0, 2, 1, 2, 2, 2, 0, 2, 1, 2, 2, 2])

In [36]:
n = len(Y_actual)

true_positive = {0: 0, 1: 0, 2: 0}
false_positive = {0: 0, 1: 0, 2: 0}
false_negative = {0: 0, 1: 0, 2: 0}
true_negative = {0: 0, 1: 0, 2: 0}

In [38]:
for i in range(n):
    for cls in [0, 1, 2]:
        if Y_actual[i] == cls and Y_pred[i] == cls:
            true_positive[cls] += 1
        elif Y_actual[i] != cls and Y_pred[i] == cls:
            false_positive[cls] += 1
        elif Y_actual[i] == cls and Y_pred[i] != cls:
            false_negative[cls] += 1
        elif Y_actual[i] != cls and Y_pred[i] != cls:
            true_negative[cls] += 1

In [47]:
accuracy_scratch = sum([true_positive[cls] for cls in [0, 1, 2]]) / n
precision_scratch = {cls: true_positive[cls] / (true_positive[cls] + false_positive[cls]) if (true_positive[cls] + false_positive[cls]) > 0 else 0 for cls in [0, 1, 2]}
recall_scratch = {cls: true_positive[cls] / (true_positive[cls] + false_negative[cls]) if (true_positive[cls] + false_negative[cls]) > 0 else 0 for cls in [0, 1, 2]}
f1_score_scratch = {cls: 2 * precision_scratch[cls] * recall_scratch[cls] / (precision_scratch[cls] + recall_scratch[cls]) if (precision_scratch[cls] + recall_scratch[cls]) > 0 else 0 for cls in [0, 1, 2]}

In [48]:
print("Metrics calculated from scratch:")
print(f"Accuracy: {accuracy_scratch}")
for cls in [0, 1, 2]:
    print(f"Class {cls} - Precision: {precision_scratch[cls]}, Recall: {recall_scratch[cls]}, F1-Score: {f1_score_scratch[cls]}")

Metrics calculated from scratch:
Accuracy: 0.7333333333333333
Class 0 - Precision: 0.7777777777777778, Recall: 0.6363636363636364, F1-Score: 0.7000000000000001
Class 1 - Precision: 0.7142857142857143, Recall: 0.625, F1-Score: 0.6666666666666666
Class 2 - Precision: 0.7142857142857143, Recall: 0.9090909090909091, F1-Score: 0.8


In [45]:
accuracy_library = accuracy_score(Y_actual, Y_pred)
precision_library = precision_score(Y_actual, Y_pred, average=None)
recall_library = recall_score(Y_actual, Y_pred, average=None)
f1_library = f1_score(Y_actual, Y_pred, average=None)

In [46]:
print("\nMetrics calculated using libraries:")
print(f"Accuracy: {accuracy_library}")
for cls, (p, r, f1) in enumerate(zip(precision_library, recall_library, f1_library)):
    print(f"Class {cls} - Precision: {p}, Recall: {r}, F1-Score: {f1}")


Metrics calculated using libraries:
Accuracy: 0.7333333333333333
Class 0 - Precision: 0.7777777777777778, Recall: 0.6363636363636364, F1-Score: 0.7
Class 1 - Precision: 0.7142857142857143, Recall: 0.625, F1-Score: 0.6666666666666666
Class 2 - Precision: 0.7142857142857143, Recall: 0.9090909090909091, F1-Score: 0.8


In [49]:
print("\nDetailed Classification Report:")
print(classification_report(Y_actual, Y_pred))


Detailed Classification Report:
              precision    recall  f1-score   support

           0       0.78      0.64      0.70        11
           1       0.71      0.62      0.67         8
           2       0.71      0.91      0.80        11

    accuracy                           0.73        30
   macro avg       0.74      0.72      0.72        30
weighted avg       0.74      0.73      0.73        30

