<a href="https://colab.research.google.com/github/2303A52158/GENERATIVE-AI_2025/blob/main/Generative_AI_2303A52158_Ass_8_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**1. (1 ponto) Design a multilayer ANN architecture according to the requirements shown below.
Train, test, save (.h5) and deploy the model to predict the quality of wine using the Keras deep
learning library**

**2. (1 ponto) Calculate training and testing accuracy, build confusion matrix, also calculate recall,
precision and F1-score.**

**3. (1 ponto) Build the application by loading the saved ANN model.**

                          Tabela 1: ANN Architecture

                    Layer      Neurons Activation Function
                Hidden Layer-1   12            tanh
                Hidden Layer-2   24            tanh
                Hidden Layer-3   30            tanh
                Hidden Layer-4   20            tanh
                Hidden Layer-5   10            tanh

                          Tabela 2: Training Parameters

                epochs-batch size error-metric Optimizer
                    200       32    accuracy     adam

In [2]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.utils import to_categorical
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

df = pd.read_csv("/content/winequality-red.csv")

X = df.drop(columns=['quality']).values
y = df['quality'].values

encoder = LabelEncoder()
y_encoded = encoder.fit_transform(y)
y_categorical = to_categorical(y_encoded)

X_train, X_test, y_train, y_test = train_test_split(X, y_categorical, test_size=0.2, random_state=42, stratify=y_encoded)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

model = Sequential([
    Dense(12, activation='tanh', input_shape=(X_train.shape[1],)),
    Dense(24, activation='tanh'),
    Dense(30, activation='tanh'),
    Dense(20, activation='tanh'),
    Dense(10, activation='tanh'),
    Dense(y_categorical.shape[1], activation='softmax')
])

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

model.fit(X_train, y_train, epochs=200, batch_size=32, validation_data=(X_test, y_test))

y_pred = model.predict(X_test)
y_pred_classes = np.argmax(y_pred, axis=1)
y_true = np.argmax(y_test, axis=1)

accuracy = accuracy_score(y_true, y_pred_classes)
conf_matrix = confusion_matrix(y_true, y_pred_classes)
report = classification_report(y_true, y_pred_classes)

print(f"Test Accuracy: {accuracy:.4f}")
print("Confusion Matrix:")
print(conf_matrix)
print("Classification Report:")
print(report)

model.save("wine_quality_model.h5")

def predict_wine_quality(features):
    model = tf.keras.models.load_model("wine_quality_model.h5")
    features = scaler.transform([features])
    prediction = model.predict(features)
    return encoder.inverse_transform([np.argmax(prediction)])

sample_features = X_test[0]
predicted_quality = predict_wine_quality(sample_features)
print(f"Predicted Wine Quality: {predicted_quality[0]}")


Epoch 1/200


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


40/40 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.2778 - loss: 1.6747 - val_accuracy: 0.5688 - val_loss: 1.3585
Epoch 2/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5895 - loss: 1.2838 - val_accuracy: 0.5875 - val_loss: 1.0917
Epoch 3/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6138 - loss: 1.0615 - val_accuracy: 0.5750 - val_loss: 1.0053
Epoch 4/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5779 - loss: 1.0364 - val_accuracy: 0.5875 - val_loss: 0.9771
Epoch 5/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6149 - loss: 0.9589 - val_accuracy: 0.5938 - val_loss: 0.9631
Epoch 6/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6198 - loss: 0.9293 - val_accuracy: 0.5875 - val_loss: 0.9551
Epoch 7/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6192 - loss: 0.9377 - val_accuracy: 0.5875 - val_loss: 0.9523
Epoch 8/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6135 - loss: 0.9342 - val_accuracy: 0.5906 - val_loss: 0.

Test Accuracy: 0.6031
Confusion Matrix:
[[ 0  0  0  2  0  0]
 [ 0  2  4  5  0  0]
 [ 2  1 85 45  3  0]
 [ 0  1 24 89 14  0]
 [ 0  0  1 21 17  1]
 [ 0  0  0  2  1  0]]
Classification Report:
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         2
           1       0.50      0.18      0.27        11
           2       0.75      0.62      0.68       136
           3       0.54      0.70      0.61       128
           4       0.49      0.42      0.45        40
           5       0.00      0.00      0.00         3

    accuracy                           0.60       320
   macro avg       0.38      0.32      0.33       320
weighted avg       0.61      0.60      0.60       320



1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step
Predicted Wine Quality: 4
