<a href="https://colab.research.google.com/github/2303A52158/GENERATIVE-AI_2025/blob/main/Generative_AI_2303A52158_Ass_8_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**1. (1 ponto) Design a multilayer ANN architecture according to the requirements shown below.
Train, test, save (.h5) and deploy the model to predict the quality of wine using the Keras deep
learning library**

**2. (1 ponto) Calculate training and testing accuracy, build confusion matrix, also calculate recall,
precision and F1-score.**

**3. (1 ponto) Build the application by loading the saved ANN model.**

                              Tabela 1: ANN Architecture
                              Layer      Neurons Activation Function
                        Hidden Layer-1     16            relu
                        Hidden Layer-2     20            relu
                        Hidden Layer-3     25            relu
                        Hidden Layer-4     10            relu
                        
                              Tabela 2: Training Parameters
                      epochs batch-size error-metric Optimizer
                        100      64        accuracy  adadelta

In [8]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.utils import to_categorical
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

df = pd.read_csv("/content/winequality-red.csv")

X = df.drop(columns=['quality']).values
y = df['quality'].values

encoder = LabelEncoder()
y_encoded = encoder.fit_transform(y)
y_categorical = to_categorical(y_encoded)

X_train, X_test, y_train, y_test = train_test_split(X, y_categorical, test_size=0.2, random_state=42, stratify=y_encoded)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

model = Sequential([
    Dense(16, activation='relu', input_shape=(X_train.shape[1],)),
    Dense(20, activation='relu'),
    Dense(25, activation='relu'),
    Dense(10, activation='relu'),
    Dense(y_categorical.shape[1], activation='softmax')
])
model.compile(optimizer='adadelta', loss='categorical_crossentropy', metrics=['accuracy'])

model.fit(X_train, y_train, epochs=100, batch_size=64, validation_data=(X_test, y_test))

y_pred = model.predict(X_test)
y_pred_classes = np.argmax(y_pred, axis=1)
y_true = np.argmax(y_test, axis=1)

accuracy = accuracy_score(y_true, y_pred_classes)
conf_matrix = confusion_matrix(y_true, y_pred_classes)
report = classification_report(y_true, y_pred_classes)

print(f"Test Accuracy: {accuracy:.4f}")
print("Confusion Matrix:")
print(conf_matrix)
print("Classification Report:")
print(report)

model.save("wine_quality_model.h5")

def predict_wine_quality(features):
    model = tf.keras.models.load_model("wine_quality_model.h5")
    features = scaler.transform([features])
    prediction = model.predict(features)
    return encoder.inverse_transform([np.argmax(prediction)])

sample_features = X_test[0]
predicted_quality = predict_wine_quality(sample_features)
print(f"Predicted Wine Quality: {predicted_quality[0]}")


Epoch 1/100


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


20/20 ━━━━━━━━━━━━━━━━━━━━ 3s 52ms/step - accuracy: 0.1393 - loss: 1.8344 - val_accuracy: 0.1594 - val_loss: 1.8412
Epoch 2/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.1361 - loss: 1.8381 - val_accuracy: 0.1625 - val_loss: 1.8410
Epoch 3/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.1277 - loss: 1.8322 - val_accuracy: 0.1625 - val_loss: 1.8409
Epoch 4/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.1288 - loss: 1.8364 - val_accuracy: 0.1625 - val_loss: 1.8407
Epoch 5/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.1241 - loss: 1.8334 - val_accuracy: 0.1656 - val_loss: 1.8405
Epoch 6/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.1272 - loss: 1.8344 - val_accuracy: 0.1688 - val_loss: 1.8404
Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.1372 - loss: 1.8320 - val_accuracy: 0.1688 - val_loss: 1.8402
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.1271 - loss: 1.8302 - val_accuracy: 0.1688 - val_loss: 1.

/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


Test Accuracy: 0.2094
Confusion Matrix:
[[ 0  0  0  0  2  0]
 [ 0  0  3  0  0  8]
 [ 0  6 39  0 43 48]
 [ 1  6 22  0 60 39]
 [ 0  4  5  0 27  4]
 [ 0  0  2  0  0  1]]
Classification Report:
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         2
           1       0.00      0.00      0.00        11
           2       0.55      0.29      0.38       136
           3       0.00      0.00      0.00       128
           4       0.20      0.68      0.31        40
           5       0.01      0.33      0.02         3

    accuracy                           0.21       320
   macro avg       0.13      0.22      0.12       320
weighted avg       0.26      0.21      0.20       320

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step
Predicted Wine Quality: 7
