<a href="https://colab.research.google.com/github/2303A52158/GENERATIVE-AI_2025/blob/main/Generative_AI_2303A52158_Ass_9_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**1. (1 ponto) Design a multilayer ANN architecture to identify the hand-written digits using the
Keras deep learning library. Consider the MNIST data set**

**2. (1 ponto) Calculate the accuracy with training and testing data**

**3. (1 ponto) Also, change the architecture by tuning no. of hidden layers, no. of hidden neurons
and activation functions in hidden layer. Identify best architecture in terms of testing accuracy**

                        Tabela 1: ANN Architecture

                        Layer       Neurons Activation Function
                  Hidden Layer - 1    32            relu
                  Hidden Layer - 2    32            relu
                  Hidden Layer - 3    32            relu

                        Tabela 2: Training Parameters

                        epochs batch-size error-metric Optimizer
                        10        128        accuracy   adadelta

In [1]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.datasets import mnist
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

(X_train, y_train), (X_test, y_test) = mnist.load_data()

X_train, X_test = X_train / 255.0, X_test / 255.0

y_train = to_categorical(y_train, 10)
y_test = to_categorical(y_test, 10)

model = Sequential([
    Flatten(input_shape=(28, 28)),
    Dense(32, activation='relu'),
    Dense(32, activation='relu'),
    Dense(32, activation='relu'),
    Dense(10, activation='softmax')
])

model.compile(optimizer='adadelta', loss='categorical_crossentropy', metrics=['accuracy'])

model.fit(X_train, y_train, epochs=10, batch_size=128, validation_data=(X_test, y_test))

y_pred = model.predict(X_test)
y_pred_classes = np.argmax(y_pred, axis=1)
y_true = np.argmax(y_test, axis=1)

accuracy = accuracy_score(y_true, y_pred_classes)
conf_matrix = confusion_matrix(y_true, y_pred_classes)
report = classification_report(y_true, y_pred_classes)

print(f"Test Accuracy: {accuracy:.4f}")
print("Confusion Matrix:")
print(conf_matrix)
print("Classification Report:")

model.save("mnist_model.h5")

def predict_digit(image):
    model = tf.keras.models.load_model("mnist_model.h5")
    image = image.reshape(1, 28, 28) / 255.0
    prediction = model.predict(image)
    return np.argmax(prediction)

sample_image = X_test[0]
predicted_digit = predict_digit(sample_image)
print(f"Predicted Digit: {predicted_digit}")


11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


/usr/local/lib/python3.11/dist-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Epoch 1/10
469/469 ━━━━━━━━━━━━━━━━━━━━ 15s 16ms/step - accuracy: 0.1007 - loss: 2.3042 - val_accuracy: 0.1114 - val_loss: 2.2959
Epoch 2/10
469/469 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - accuracy: 0.1138 - loss: 2.2926 - val_accuracy: 0.1263 - val_loss: 2.2833
Epoch 3/10
469/469 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.1304 - loss: 2.2790 - val_accuracy: 0.1481 - val_loss: 2.2713
Epoch 4/10
469/469 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.1522 - loss: 2.2686 - val_accuracy: 0.1736 - val_loss: 2.2594
Epoch 5/10
469/469 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.1790 - loss: 2.2562 - val_accuracy: 0.2004 - val_loss: 2.2476
Epoch 6/10
469/469 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.2068 - loss: 2.2448 - val_accuracy: 0.2230 - val_loss: 2.2355
Epoch 7/10
469/469 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.2310 - loss: 2.2325 - val_accuracy: 0.2449 - val_loss: 2.2229
Epoch 8/10
469/469 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.2559 - loss: 2.2196 - val_accuracy: 

Test Accuracy: 0.3120
Confusion Matrix:
[[718   0   1   0  44   4  57   0 143  13]
 [  6 622  12   1  14   8  76   0 381  15]
 [130 163  93   0 144   3 335   0 109  55]
 [319  83  56  21  64  15 161   1 140 150]
 [ 22  11   0   0 111  12 274   3 140 409]
 [276  29  12   5  33  16 186   0 260  75]
 [118   1   1   0 202   3 472   7  95  59]
 [ 12  78  32   2  67  19 147  29  72 570]
 [ 69 196   2   0  31   8 105   0 532  31]
 [ 21  25   9   0  94  23 230   4  97 506]]
Classification Report:
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 162ms/step
Predicted Digit: 2
