<a href="https://colab.research.google.com/github/2303A52158/GENERATIVE-AI_2025/blob/main/Generative_AI_2303A52158_Ass_9_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**1. (1 ponto) Design a multilayer ANN architecture to identify the hand-written digits using the
Keras deep learning library. Consider the MNIST data set**

**2. (1 ponto) Calculate the accuracy with training and testing data**

**3. (1 ponto) Also, change the architecture by tuning no. of hidden layers, no. of hidden neurons
and activation functions in hidden layer. Identify best architecture in terms of testing accuracy**

                    Tabela 1: ANN Architecture
          Layer          Neurons Activation Function
      Hidden Layer - 1     128         swish
      Hidden Layer - 2     128         swish
      Hidden Layer - 3     128         swish

                    Tabela 2: Training Parameters
          epochs batch size error metric Optimizer
            30        32      accuracy     adam

In [1]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.datasets import mnist
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

(X_train, y_train), (X_test, y_test) = mnist.load_data()

X_train, X_test = X_train / 255.0, X_test / 255.0

y_train = to_categorical(y_train, 10)
y_test = to_categorical(y_test, 10)

model = Sequential([
    Flatten(input_shape=(28, 28)),
    Dense(128, activation='swish'),
    Dense(128, activation='swish'),
    Dense(128, activation='swish'),
    Dense(10, activation='softmax')
])

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

model.fit(X_train, y_train, epochs=30, batch_size=32, validation_data=(X_test, y_test))

y_pred = model.predict(X_test)
y_pred_classes = np.argmax(y_pred, axis=1)
y_true = np.argmax(y_test, axis=1)

accuracy = accuracy_score(y_true, y_pred_classes)
conf_matrix = confusion_matrix(y_true, y_pred_classes)
report = classification_report(y_true, y_pred_classes)

print(f"Test Accuracy: {accuracy:.4f}")
print("Confusion Matrix:")
print(conf_matrix)
print("Classification Report:")

model.save("mnist_model.h5")

def predict_digit(image):
    model = tf.keras.models.load_model("mnist_model.h5")
    image = image.reshape(1, 28, 28) / 255.0
    prediction = model.predict(image)
    return np.argmax(prediction)

sample_image = X_test[0]
predicted_digit = predict_digit(sample_image)
print(f"Predicted Digit: {predicted_digit}")


11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


/usr/local/lib/python3.11/dist-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Epoch 1/30
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - accuracy: 0.8781 - loss: 0.4151 - val_accuracy: 0.9630 - val_loss: 0.1126
Epoch 2/30
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 19s 5ms/step - accuracy: 0.9695 - loss: 0.1017 - val_accuracy: 0.9722 - val_loss: 0.0905
Epoch 3/30
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.9793 - loss: 0.0636 - val_accuracy: 0.9754 - val_loss: 0.0816
Epoch 4/30
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - accuracy: 0.9855 - loss: 0.0448 - val_accuracy: 0.9752 - val_loss: 0.0857
Epoch 5/30
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - accuracy: 0.9871 - loss: 0.0378 - val_accuracy: 0.9734 - val_loss: 0.0927
Epoch 6/30
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - accuracy: 0.9911 - loss: 0.0277 - val_accuracy: 0.9806 - val_loss: 0.0791
Epoch 7/30
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.9931 - loss: 0.0223 - val_accuracy: 0.9756 - val_loss: 0.0985
Epoch 8/30
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - accuracy: 0.9928 - loss: 0.0224

Test Accuracy: 0.9769
Confusion Matrix:
[[ 961    0    2    0    1    1   10    3    1    1]
 [   0 1120    3    1    2    2    2    2    3    0]
 [   0    0 1021    2    1    0    1    4    3    0]
 [   0    0    6  981    0    2    0    8    2   11]
 [   0    0    3    0  963    0    4    3    2    7]
 [   0    0    0   13    0  864    4    1    4    6]
 [   1    3    1    1    8    4  935    0    4    1]
 [   0    2   14    0    1    0    0 1006    2    3]
 [   1    0   13    5    2    3    3    4  938    5]
 [   0    2    0    5   10    2    1    7    2  980]]
Classification Report:
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step
Predicted Digit: 5
